
# Sirve para probar la API, algo asi como lo q hace postman

@baseUrl = http://localhost:4568/

#############################################

# POST {{baseUrl}}usuario/validar 
# content-type: application/json

# {
#   "usuario": "20210109",
#   "contrasenia": "123"
# }

#############################################
# POST {{baseUrl}}usuario/cambiar-contrasenia
# Content-Type: application/x-www-form-urlencoded

# correo=45954@aloe.ulima.edu.pe

#############################################
GET {{baseUrl}}usuarios



GET {{baseUrl}}usuarios/1
